[data]
src_file = ./data/input/latest-covid-data.csv
load_file = ./data/output/covid-analysis-result.csv

[api]
host = covid19-data.p.rapidapi.com
secret_key = **
countries = Antigua and Barbuda,Albania,Armenia,Angola,Argentina,Austria,Australia,Azerbaijan,Bosnia and Herzegovina,Barbados,Bangladesh,Belgium,Burkina Faso,Bulgaria,Bahrain,Burundi,Benin,Bolivia,Brazil,Bahamas
